baseurl = "http://example.com/"
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	github = "https://github.com/alexurquhart"
	twitter = "https://twitter.com/alexanderurq"
	linkedin = "https://www.linkedin.com/profile/view?id=339355941"
	email = "alexurquhart@gmail.com"
	
	profilepic = "img/profile.png"
	
	title = "MY NAME"
	subtitle = "MY HUGO BLOG"
	
	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"
